displayName=Pet Resizer
author=KihiraLove
description=Resize your follower or all nearby pets without changing clickboxes (requires RuneLite GPU)
tags=pet,resize
version=
plugins=com.petresizer.PetResizer
build=standard
