package com.petresizer;

import net.runelite.api.NPC;
import net.runelite.api.NPCComposition;
import net.runelite.api.gameval.NpcID;

final class PetNpcs
{
	private PetNpcs()
	{
	}

	static boolean isPet(NPC npc)
	{
		NPCComposition composition = npc.getTransformedComposition();
		if (composition == null)
		{
			composition = npc.getComposition();
		}
		return composition != null && composition.isFollower()
			|| PetFilters.isDog(npc)
			|| isPohPet(npc.getId())
			|| composition != null && isPohPet(composition.getId());
	}

	// Menagerie variants are not necessarily marked as followers. Keep an
	// explicit gameval list: POH dungeon monsters and servants are not pets.
	private static boolean isPohPet(int id)
	{
		switch (id)
		{
			case NpcID.POH_COREPET:
			case NpcID.POH_SKOTIZO_PET:
			case NpcID.POH_VENENATIS_PET:
			case NpcID.POH_CALLISTO_PET:
			case NpcID.POH_HELLPET:
			case NpcID.POH_SNAKE_PET_GREEN:
			case NpcID.POH_SNAKE_PET_ORANGE:
			case NpcID.POH_SNAKE_PET_BLUE:
			case NpcID.POH_MENAGERIE_SARACHNISPET:
			case NpcID.POH_SKILLPET_MINING_AMETHYST:
			case NpcID.POH_SOULWARS_PET_BLUE:
			case NpcID.POH_PHOENIX_PET_GREEN:
			case NpcID.POH_PHOENIX_PET_BLUE:
			case NpcID.POH_PHOENIX_PET_WHITE:
			case NpcID.POH_PHOENIX_PET_PURPLE:
			case NpcID.POH_SOULWARS_PET_RED:
			case NpcID.POH_CHOMPYBIRD_PET:
			case NpcID.POH_VETION_PET:
			case NpcID.POH_VETION_PET_2:
			case NpcID.POH_SCORPIA_PET:
			case NpcID.POH_ABYSSALSIRE_PET:
			case NpcID.POH_JADPET:
			case NpcID.POH_CHAOS_ELEMENTAL_PET:
			case NpcID.POH_BLOODHOUNDPET:
			case NpcID.POH_SUPREME_PET:
			case NpcID.POH_PRIME_PET:
			case NpcID.POH_REX_PET:
			case NpcID.POH_PENANCE_PET:
			case NpcID.POH_ARMADYL_PET:
			case NpcID.POH_BANDOS_PET:
			case NpcID.POH_SARADOMIN_PET:
			case NpcID.POH_ZAMORAK_PET:
			case NpcID.POH_MOLE_PET:
			case NpcID.POH_KBD_PET:
			case NpcID.POH_KQ_PET_FLYING:
			case NpcID.POH_KQ_PET_WALKING:
			case NpcID.POH_SMOKE_PET:
			case NpcID.POH_KRAKEN_PET:
			case NpcID.POH_ROCK:
			case NpcID.POH_FISHBOWL_BLUEFISH:
			case NpcID.POH_FISHBOWL_GREENFISH:
			case NpcID.POH_FISHBOWL_SPINEFISH:
			case NpcID.POH_TOY_CAT_MENAGERIE:
			case NpcID.POH_GROWNCAT_DEFAULT:
			case NpcID.POH_GROWNCAT_LIGHT:
			case NpcID.POH_GROWNCAT_BROWN:
			case NpcID.POH_GROWNCAT_BLACK:
			case NpcID.POH_GROWNCAT_BROWNGREY:
			case NpcID.POH_GROWNCAT_BLUEGREY:
			case NpcID.POH_GROWNCAT_HELL:
			case NpcID.POH_OVERGROWNCAT_DEFAULT:
			case NpcID.POH_OVERGROWNCAT_LIGHT:
			case NpcID.POH_OVERGROWNCAT_BROWN:
			case NpcID.POH_OVERGROWNCAT_BLACK:
			case NpcID.POH_OVERGROWNCAT_BROWNGREY:
			case NpcID.POH_OVERGROWNCAT_BLUEGREY:
			case NpcID.POH_OVERGROWNCAT_HELL:
			case NpcID.POH_LAZYCAT_DEFAULT:
			case NpcID.POH_LAZYCAT_LIGHT:
			case NpcID.POH_LAZYCAT_BROWN:
			case NpcID.POH_LAZYCAT_BLACK:
			case NpcID.POH_LAZYCAT_BROWNGREY:
			case NpcID.POH_LAZYCAT_BLUEGREY:
			case NpcID.POH_LAZYCAT_HELL:
			case NpcID.POH_WILEYCAT_DEFAULT:
			case NpcID.POH_WILEYCAT_LIGHT:
			case NpcID.POH_WILEYCAT_BROWN:
			case NpcID.POH_WILEYCAT_BLACK:
			case NpcID.POH_WILEYCAT_BROWNGREY:
			case NpcID.POH_WILEYCAT_BLUEGREY:
			case NpcID.POH_WILEYCAT_HELL:
			case NpcID.POH_SKILLPET_FISH:
			case NpcID.POH_SKILLPET_HUNTER_RED:
			case NpcID.POH_SKILLPET_HUNTER_GREY:
			case NpcID.POH_SKILLPET_HUNTER_BLACK:
			case NpcID.POH_SKILLPET_HUNTER_GOLD:
			case NpcID.POH_SKILLPET_FISH_TEMPOROSS:
			case NpcID.POH_SCURRIUS_PET:
			case NpcID.POH_SKILLPET_AGILITY:
			case NpcID.POH_SKILLPET_FARMING:
			case NpcID.POH_SKILLPET_THIEVING:
			case NpcID.POH_SKILLPET_RUNECRAFTING_FIRE:
			case NpcID.POH_SKILLPET_RUNECRAFTING_AIR:
			case NpcID.POH_SKILLPET_RUNECRAFTING_MIND:
			case NpcID.POH_SKILLPET_RUNECRAFTING_WATER:
			case NpcID.POH_SKILLPET_RUNECRAFTING_EARTH:
			case NpcID.POH_SKILLPET_RUNECRAFTING_BODY:
			case NpcID.POH_SKILLPET_RUNECRAFTING_COSMIC:
			case NpcID.POH_SKILLPET_RUNECRAFTING_CHAOS:
			case NpcID.POH_SKILLPET_RUNECRAFTING_NATURE:
			case NpcID.POH_SKILLPET_RUNECRAFTING_LAW:
			case NpcID.POH_SKILLPET_RUNECRAFTING_DEATH:
			case NpcID.POH_SKILLPET_RUNECRAFTING_SOUL:
			case NpcID.POH_SKILLPET_RUNECRAFTING_ASTRAL:
			case NpcID.POH_SKILLPET_RUNECRAFTING_BLOOD:
			case NpcID.POH_PHOENIX_PET:
			case NpcID.POH_SKILLPET_MINING_DEFAULT:
			case NpcID.POH_SKILLPET_MINING_TIN:
			case NpcID.POH_SKILLPET_MINING_COPPER:
			case NpcID.POH_SKILLPET_MINING_IRON:
			case NpcID.POH_SKILLPET_MINING_BLURITE:
			case NpcID.POH_SKILLPET_MINING_SILVER:
			case NpcID.POH_SKILLPET_MINING_COAL:
			case NpcID.POH_SKILLPET_MINING_GOLD:
			case NpcID.POH_SKILLPET_MINING_MITHRIL:
			case NpcID.POH_SKILLPET_MINING_GRANITE:
			case NpcID.POH_SKILLPET_MINING_ADAMANTITE:
			case NpcID.POH_SKILLPET_MINING_RUNITE:
			case NpcID.POH_OLM_PET:
			case NpcID.POH_INFERNO_PET:
			case NpcID.POH_SKILLPET_MINING_LOVAKITE:
			case NpcID.POH_SKILLPET_MINING_ELEMENTAL:
			case NpcID.POH_SKILLPET_MINING_DAEYALT:
			case NpcID.POH_HERBIBOAR_PET:
			case NpcID.POH_DUSK_PET:
			case NpcID.POH_DAWN_PET:
			case NpcID.POH_CORPPET:
			case NpcID.POH_ZUK_PET:
			case NpcID.POH_SKILLPET_RUNECRAFTING_WRATH:
			case NpcID.POH_VORKATH_PET:
			case NpcID.POH_NIGHTMARE_PET_PARASITE:
			case NpcID.POH_DOGADILE_PET:
			case NpcID.POH_TEKTON_PET:
			case NpcID.POH_VANGUARD_PET:
			case NpcID.POH_VASA_PET:
			case NpcID.POH_VESPULA_PET:
			case NpcID.POH_VERZIK_PET:
			case NpcID.POH_SMOKE_PET_OLD:
			case NpcID.POH_HYDRA_PET:
			case NpcID.POH_HYDRA_PET_ELECTRIC:
			case NpcID.POH_HYDRA_PET_FIRE:
			case NpcID.POH_HYDRA_PET_EXTINGUISHED:
			case NpcID.POH_GAUNTLET_PET:
			case NpcID.POH_GAUNTLET_PET_CORRUPT:
			case NpcID.POH_ZALCANO_PET:
			case NpcID.POH_NIGHTMARE_PET:
			case NpcID.POH_SKILLPET_FARMING_CRYSTAL:
			case NpcID.POH_SKILLPET_FARMING_DRAGON:
			case NpcID.POH_SKILLPET_FARMING_HERB:
			case NpcID.POH_SKILLPET_FARMING_LILY:
			case NpcID.POH_SKILLPET_FARMING_REDWOOD:
			case NpcID.POH_TEKTON_ENRAGED_PET:
			case NpcID.POH_VESPULA_FLYING_PET:
			case NpcID.POH_SKILLPET_AGILITY_DARK:
			case NpcID.POH_SKILLPET_THIEVING_PANDA:
			case NpcID.POH_SKILLPET_THIEVING_TANUKI:
			case NpcID.POH_RTBRANDA_PET:
			case NpcID.POH_TEMPOROSS_PET:
			case NpcID.POH_JADPET_INFERNO:
			case NpcID.POH_MOLE_PET_NAKED:
			case NpcID.POH_VERZIK_PET_MAIDEN:
			case NpcID.POH_VERZIK_PET_BLOAT:
			case NpcID.POH_VERZIK_PET_NYLOCAS:
			case NpcID.POH_VERZIK_PET_SOTETSEG:
			case NpcID.POH_VERZIK_PET_XARPUS:
			case NpcID.POH_MENAGERIE_SARACHNISPET_ORANGE:
			case NpcID.POH_MENAGERIE_SARACHNISPET_BLUE:
			case NpcID.POH_NEX_PET:
			case NpcID.POH_SKILLPET_RUNECRAFTING_GOTR:
			case NpcID.POH_ABYSSAL_PET:
			case NpcID.POH_WARDEN_PET_TUMEKEN:
			case NpcID.POH_WARDEN_PET_ELIDINIS:
			case NpcID.POH_WARDEN_PET_AKKHA:
			case NpcID.POH_WARDEN_PET_BABA:
			case NpcID.POH_WARDEN_PET_KEPHRI:
			case NpcID.POH_WARDEN_PET_ZEBAK:
			case NpcID.POH_WARDEN_PET_TUMEKEN_DESTROYED:
			case NpcID.POH_WARDEN_PET_ELIDINIS_DESTROYED:
			case NpcID.POH_VENENATIS_PET_LEGACY:
			case NpcID.POH_CALLISTO_PET_LEGACY:
			case NpcID.POH_VETION_PET_LEGACY:
			case NpcID.POH_VETION_PET_2_LEGACY:
			case NpcID.POH_MUSPAH_PET:
			case NpcID.POH_MUSPAH_PET_MELEE:
			case NpcID.POH_MUSPAH_PET_SHIELDED:
			case NpcID.POH_WHISPERER_PET:
			case NpcID.POH_VARDORVIS_PET:
			case NpcID.POH_DUKE_SUCELLUS_PET:
			case NpcID.POH_LEVIATHAN_PET:
			case NpcID.POH_SKILLPETWC:
			case NpcID.POH_SKILLPET_WC_OAK:
			case NpcID.POH_SKILLPET_WC_WILLOW:
			case NpcID.POH_SKILLPET_WC_MAPLE:
			case NpcID.POH_SKILLPET_WC_YEW:
			case NpcID.POH_SKILLPET_WC_MAGIC:
			case NpcID.POH_SKILLPET_WC_REDWOOD:
			case NpcID.POH_SKILLPET_WC_TEAK:
			case NpcID.POH_SKILLPET_WC_MAHOGANY:
			case NpcID.POH_SKILLPET_WC_ARCTIC:
			case NpcID.POH_SKILLPET_WC_PHEASANT:
			case NpcID.POH_SKILLPET_WC_FOX:
			case NpcID.POH_RTELDRIC_PET:
			case NpcID.POH_SOLHEREDIT_PET:
			case NpcID.POH_QUETZAL_PET:
			case NpcID.POH_BROAV:
			case NpcID.POH_ARAXXOR_PET:
			case NpcID.POH_ARAXXOR_PET_CUTE:
			case NpcID.POH_SKILLPET_AGILITY_BONE:
			case NpcID.POH_HUEY_PET:
			case NpcID.POH_AMOXLIATL_PET:
			case NpcID.POH_YAMA_PET:
			case NpcID.POH_EGG:
			case NpcID.POH_DOM_PET:
			case NpcID.POH_HW_CHAIR:
			case NpcID.POH_FISHBOWL_MAYOR_OF_CATHERBY:
			case NpcID.POH_SKILLPET_MINING_LEAD:
			case NpcID.POH_SKILLPET_MINING_RUBIUM:
			case NpcID.POH_SKILLPET_MINING_NICKEL:
			case NpcID.POH_SKILLPET_WC_CAMPHOR:
			case NpcID.POH_SKILLPET_WC_IRONWOOD:
			case NpcID.POH_SKILLPET_WC_JATOBA:
			case NpcID.POH_SKILLPET_WC_ROSEWOOD:
			case NpcID.POH_SKILLPET_SAILING:
			case NpcID.POH_GRYPHONBOSS_PET:
			case NpcID.POH_GRYPHONBOSS_PET_ADULT:
			case NpcID.POH_EASTER26_EGG:
			case NpcID.POH_EASTER26_EGG_02:
			case NpcID.POH_EASTER26_EGG_03:
			case NpcID.POH_EASTER26_EGG_04:
			case NpcID.POH_EASTER26_EGG_05:
			case NpcID.POH_EASTER26_EGG_06:
			case NpcID.POH_EASTER26_EGG_07:
			case NpcID.POH_COWBOSS_PET:
			case NpcID.POH_MAGGOT_KING_PET:
			case NpcID.POH_GOAT_PIT_PET:
			case NpcID.POH_MAD_ANGEL_PET:
				return true;
			default:
				return false;
		}
	}
}
